workflows:
  flutter-workflow:
    name: Flutter Workflow no ambiente ${ambiente} - GMUD ${gmud}
    environment:
      flutter: ${flutterversion}
      xcode: latest # se for necessário para builds iOS, ajuste conforme sua necessidade
    scripts:
      # Passo 1: Instalar o osv-scanner usando Homebrew
      - name: Install Homebrew
        script: |
          if ! command -v brew &> /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi

      - name: Install osv-scanner
        script: |
          brew install osv-scanner

      # Passo 2: Executar o osv-scanner no pubspec.yaml
      - name: Run SCA with osv-scanner
        script: |
          osv-scanner --lockfile=pubspec.lock

      # Passo 3: Continuar com o build apenas se o scanner passar sem vulnerabilidades
      - name: Flutter build
        script: |
          if [ $? -eq 0 ]; then
            flutter build apk --release # ou `flutter build ios` para builds iOS
          else
            echo "Vulnerabilities found in pubspec.lock. Aborting build."
            exit 1
          fi
